# Project exclude paths
stages:
  - sonar
  - build

sonar:
  stage: sonar
  image: hub.iquantex.com/base/maven:3.6.3-jdk8-helm3
  script:
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean install -Dmaven.test.skip=true && mvn sonar:sonar
  only:
    - develop
  tags:
    - sigma-dev

build:
  stage: build
  script:
    - mvn compile && mvn package && mvn deploy
  only:
    - develop
    - /(ci\-)+.*$/
    - tags

